#!/usr/bin/env bash
# temper-structure-check.sh — PreToolUse hook for Write
#
# Enforces Temper project structure rules:
# - All .temper.md source files must be in src/ (flat, no subdirectories)
# - Sibling modules cause parallel @I stage failures
# - Test files must follow *_test.temper.md naming convention
#
# Exit 0 = allow
# Exit 2 = block

set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

# Only check .temper.md files
if [[ ! "$FILE_PATH" == *.temper.md ]]; then
  exit 0
fi

# Skip config.temper.md at root — that's valid
BASENAME=$(basename "$FILE_PATH")
if [[ "$BASENAME" == "config.temper.md" ]]; then
  exit 0
fi

PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // empty')
if [[ -z "$PROJECT_DIR" ]]; then
  PROJECT_DIR="/Users/robertgrayson/code/generic_temper_orm"
fi

SRC_DIR="${PROJECT_DIR}/src"

# ─── CHECK 1: .temper.md files must be in src/ ───
FILE_DIR=$(dirname "$FILE_PATH")
if [[ "$FILE_DIR" != "$SRC_DIR" ]]; then
  # Check if it's a subdirectory of src/
  if [[ "$FILE_DIR" == "$SRC_DIR/"* ]]; then
    cat >&2 << 'EOF'
BLOCKED: Cannot create .temper.md files in subdirectories of src/.

Temper processes sibling modules' @I (import) stage in parallel.
This means cross-module imports between subdirectories FAIL at compile time.

All source files must be FLAT in src/ (no subdirectories).
Files in the same directory share scope automatically — no imports needed.

Move this file to src/ instead.
EOF
    exit 2
  fi

  # Check if it's somewhere else entirely
  if [[ "$FILE_DIR" != "$PROJECT_DIR" ]]; then
    cat >&2 << EOF
BLOCKED: .temper.md source files should be in ${SRC_DIR}/.

The project uses a flat module structure:
  - config.temper.md → project root (library name definition)
  - src/*.temper.md → all source and test files (flat)

Do not create .temper.md files outside these locations.
EOF
    exit 2
  fi
fi

# ─── CHECK 2: Test file naming convention ───
CONTENT=$(echo "$INPUT" | jq -r '.tool_input.content // empty')
if echo "$CONTENT" | grep -q 'test('; then
  if [[ ! "$BASENAME" == *_test.temper.md ]]; then
    cat << EOF
WARNING: File '$BASENAME' contains test() calls but doesn't follow
the naming convention '*_test.temper.md'.

Test files should be named: <module>_test.temper.md
Examples: schema_test.temper.md, query_test.temper.md

This helps identify test files and keeps them organized.
EOF
  fi
fi

# ─── CHECK 3: Don't modify temper.keep/ name-selection.json carelessly ───
if [[ "$FILE_PATH" == *temper.keep* ]] && [[ "$FILE_PATH" == *name-selection.json ]]; then
  cat << 'EOF'
WARNING: Modifying name-selection.json in temper.keep/.
These files control backend name mappings and are generated by the compiler.
Manual edits may cause name resolution failures across backends.
Only modify if you understand the cross-backend naming implications.
EOF
fi

exit 0
